name: strata_builder
description: Builder and code generator for strata (Ecto-inspired data mapping) schemas.
version: 0.1.0
publish_to: none
repository: https://github.com/tugorez/strata
issue_tracker: https://github.com/tugorez/strata/issues

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  strata:
    path: ../strata
  strata_sqlite:
    path: ../strata_sqlite
  analyzer: ^8.4.1
  build: ^4.0.2
  code_builder: ^4.11.0
  dart_style: ^3.1.2
  source_gen: ^4.0.2
  glob: ^2.1.2
  path: ^1.9.1
  args: ^2.6.0

dev_dependencies:
  build_runner: ^2.10.1
  lints: ^6.0.0
  test: ^1.25.6

executables:
  create_migration:
